### ISSUE TITLE
Admonishments odd behaviour

### ISSUE THREAD

**Issue by pmatulis** [canonical-webteam/discoursifier#10]
When editing a post with an admonishment of type 'negative' or 'important' the draft pane shows text boxes in red and blue, respectively, as expected/desired. However, these colours turn to grey once the post is saved. I'm seeing this in the draft Juju Discourse site.

**Comment by nottrobin** [comment]
What is the draft site?

**Comment by nottrobin** [comment]
It seems this now works.
