### ISSUE TITLE
Tables are truncated

### ISSUE THREAD

**Issue by pmatulis** [canonical-webteam/discoursifier#6]
The [Configuring controllers](https://docs.jujucharms.com/2.5/en/controllers-config) page has a big table and the rightmost column has its contents truncated once discoursified. Probably the same for the  [Configuring models](https://docs.jujucharms.com/2.5/en/models-config) page but that page couldn't be discoursified and therefore lacks confirmation (due to the duplicate titles issue).

**Comment by nottrobin** [comment]
This was also raised [in docs.snapcraft.io](https://github.com/canonical-websites/docs.snapcraft.io/issues/58). I'm afraid there's no easy or sensible way to display large tables like this in Discourse. The preference over there was to find a way to restructure the content, and I hope we can do the same here. Either way, I don't think there's anything I can do in the import itself, we'll have to iterate on it after it's imported.
