### ISSUE TITLE
Foldouts are not converted

### ISSUE THREAD

**Issue by pmatulis** [canonical-webteam/discoursifier#7]
The expandable triangle thingies need to be converted. A sample page is the [Models](https://docs.jujucharms.com/2.5/en/models) page.

**Comment by nottrobin** [comment]
Discourse doesn't support foldouts in Markdown.

You can use [an HTML `<details>` element](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d), e.g.:

---

``` html
<details>
 <summary>Summary Goes Here</summary>
 ...this is hidden, <i>collapsable</i> content...
</details>
```

<details>
 <summary>Summary Goes Here</summary>
 ...this is hidden, <i>collapsable</i> content...
</details>

---

The problem with this is that you then can't use Markdown syntax inside the `<details></details>` block - this whole content will have to be represented with HTML.

How many of these foldouts are there? 'Cos unless there are more than 10, I suspect it would be much quicker to convert these manually after the import than try to write an automated converter.

**Comment by pmatulis** [comment]
58

**Comment by nottrobin** [comment]
okay then I guess we do need to automate something. That's a pain.
